### ISSUE TITLE
Can we Extract data from MSSQL database and load it into a csv file?

### ISSUE THREAD

**Issue by thangasujithas** [wizacode/php-etl#100]
Using this library Can we Extract data from MSSQL database and load it into a csv file?

**Comment by ecourtial** [comment]
Hi @thangasujithas I never tried but there is a connector so I guess yes : https://github.com/wizaplace/php-etl/tree/master/src/Database/Connectors

**Comment by chriscalip** [comment]
It wont work because https://github.com/wizacode/php-etl/blob/master/src/Database/Connectors/SqlServerConnector.php#L55 is using deprecated code now. 
See screeenshot for example.
![wizacode-mssql-etl](https://user-images.githubusercontent.com/479454/165445138-9f1a1dde-931d-483c-9588-44dca860d5bc.png)

**Comment by ecourtial** [comment]
Hi @chriscalip and thank you for your message.

I am not sure to understand: in your screenshot I don't see any deprecation notice (on top of that, deprecation should not prevent the code to work).

However when looking at your screenshot, I see the error _could not find driver_, usually meaning that the proper PDO extension is not installed.

Do you have any information to help us to understand?

**Comment by ecourtial** [comment]
Closing since no news for months.
