### ISSUE TITLE
Complete example, with DB connection?

### ISSUE THREAD

**Issue by cxj** [wizacode/php-etl#97]
Does anyone have a complete example, no matter how simple, which includes database connections?  I am unable to figure out how to get my database configuration into the `Table` class via the `Manager` and `ConnectionFactory` so that my program can actually read one database and write another.

**Comment by ecourtial** [comment]
@kdebisschop Do you have something on your side ?

**Comment by ecourtial** [comment]
@cxj What issue are you facing?

A quick look to the code (I am not an expert with this very specific part of the library): you have to use the _Table_ extractor directly. As you can see in this class, it will use the _default_ connection.

At first sight : 
- Instantiate the _Table_ class
- Call the _input_ method to set the table to read
- Then launch the ETL workflow : the extract method will be called.

**Note 1**: if you use a framework like Symfony or Laravel, it will be easier to configure everything and getting directly a _Table_ instance. Otherwise, you will have to look inside each class to see what they need : _Table_ need a _Manager_ and this latter need a _ConnectionFactory_. And you obviously need to add the connection via calling the _addConnection()_ method of the _Manager_.

**Note 2**: as you can see in the code, the _Table_ extractor will extract all the fields of the SQL table. If it is too resource consuming, you can easily extends this class to be more specific.

Let us know if you need more help :)

**Comment by cxj** [comment]
Thanks much for the reply and follow-up.  I've been buried with other things.  

I am using Laravel.  I did get an ETL to CSV working by using something like this bit hacking.  Looking back on my experiment, I don't think I managed to make a Load to database work, but imagine a second `$config` set up would do it.  I'd prefer to just refer to my Laravel connection names, than to repeat them this way, however.  I'll try to experiment with it a bit more later this evening.  Will report back here what I find.

```php
    $config = [
            'driver'    => 'mysql',
            'host'      => Config::get('database.connections.msp.host'),
            'port'      => '3306',
            'database'  => Config::get('database.connections.msp.database'),
            'username'  => Config::get('database.connections.msp.username'),
            'password'  => Config::get('database.connections.msp.password'),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
        ];

        $manager = new Manager(new ConnectionFactory());
        $manager->addConnection($config);
        $etl = new Etl();
        $query        = new Query($manager);
        $sql          = <<<
-- SELECT query omitted
SQL;
        $etl->extract($query, $sql, $queryOptions);

        $csvLoader  = new CsvLoader();
        $csvOptions = [CsvLoader::LINE_PER_FILE => 1000];
        $etl->load($csvLoader, 'outputFileName.csv', $csvOptions);
        $etl->run();
```

**Comment by herbdool** [comment]
I noticed that the basic example in the README.md is missing this line:

```
$manager->addConnection($config);
```

I had figured it out eventually on my own, but would be good to update the document so it's complete.

**Comment by ecourtial** [comment]
> ```
> $manager->addConnection($config);
> ```

Thank you @herbdool, we have just updated the documentation.
